import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module'

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit official Pikchr Site:
https://pikchr.org
The github repository of this wrapper plugin:
https://github.com/notlibrary/obsidian-adamantine-pick
*/
`;

const prod = (process.argv[2] === 'production');

const options = {
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	loader: { ".wasm": "binary" },
	external: [
		"obsidian",
		"electron",
		"node:fs",
		...builtinModules],
	format: 'cjs',
	target: 'es2021',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	minify: prod ? true : false,
	treeShaking: true,
	outfile: 'main.js',
};

if (prod) {
  esbuild.build(options).catch(() => process.exit(1));
} else {
  let context = await esbuild.context(options);
  context.watch().catch(() => process.exit(1));
}
